### ISSUE TITLE
ROBOKOP  query error if bogus ID

### ISSUE THREAD

**Issue by karafecho** [RobokopU24/Issues#167]
This issue is to report a ROBOKOP error that I received earlier today. 

![image](https://github.com/RobokopU24/Feedback/assets/26254388/db0424fa-3457-4ebd-b9ca-04360c59c601)

I reproduced the issue when entering the UNII id later in the day and after modifying it with the UNIPROT.ISOFORM prefix. 

I was able to resolve the issue after pulling the preferred identifier from Node Norm or entering the name ("Immunoglobulin E") from the drop-down menu, although ROBOKOP stated that there were no answers linking IgE to asthma, which seems odd to me.

Specific concerns are as follows:

(1) A regular ROBOKOP user will not want to do all of this troubleshooting.
(2) A user shouldn't be able to select an identifier or name for an entity that does not exist as a node in the underlying KG.
(3) I would have expected to find a NamedThing (e.g., biological process, phenotype, chemical, drug) that relates asthma and IgE.

**Comment by cbizon** [comment]
1) It's not totally clear to me what this one is - would it be solved by 2?
2) Agreed. See #138 
3) I don't think UNII:P01854 is an id?  Because of (2) it's all but impossible to construct the right query through robokop, but if I look in the KG itself, I can see that  there are a couple of connections.  Not very interesting ones:
<img width="490" alt="image" src="https://github.com/RobokopU24/Feedback/assets/10744350/d3cbdda8-841c-4e14-9187-5dfe5a451b89">


These are the things connected to IGE:


1 | "GO:0050853" | "B cell receptor signaling pathway" | "biolink:actively_involved_in"
2 | "GO:0006955" | "immune response" | "biolink:actively_involved_in"
3 | "GO:0006954" | "inflammatory response" | "biolink:actively_involved_in"
4 | "GO:0002250" | "adaptive immune response" | "biolink:actively_involved_in"
5 | "GO:0003823" | "antigen binding" | "biolink:enables"
6 | "GO:0071742" | "IgE immunoglobulin complex" | "biolink:has_part"
7 | "GO:0005576" | "extracellular region" | "biolink:located_in"
8 | "GO:0005615" | "extracellular space" | "biolink:located_in"
9 | "GO:0005886" | "plasma membrane" | "biolink:located_in"
10 | "MESH:D000069444" | "Omalizumab" | "biolink:binds"

So it seems to me that one big problem is that asthma is not connected to the right GO terms.  I suspect that we could get a better set from ubergraph than we currently have.  Will make a separate issue for that.

@karafecho I'm assuming that the error above is because of the identifier issue, but tell me if I'm misunderstanding

**Comment by karafecho** [comment]
Yes, I believe the proposed solution in #138 would have avoided this issue. The UNII id was provided by a SME. As noted, I was able to resolve the issue by leveraging SRI services or by entering a less specific name ("Immunoglobulin E" instead of "Immunoglobulin heavy chain constant E"), but both workarounds aren't ideal, imo.

**Comment by cbizon** [comment]
Closing as #138 has been implemented
