### ISSUE TITLE
Text Mining Provider

### ISSUE THREAD

**Issue by karafecho** [RobokopU24/Issues#190]
This issue is to report an issue with automat-text-mining-provider. Specifically, Bill Baumgartner mentioned that the Automat version of Text Mining Provider is significantly outdated and should not be used. I clarified after today's ROBOKOP call that the issue is NOT related to targeted vs co-occurrence, but rather related issues that have since been fixed. We will need to update our source data.

```
- id: infores:automat-text-mining-provider
    status: deprecated
    name: Automat Textmining KP
    knowledge level: curated
    agent type: not_provided
    description: A literature co-occurrence graph created by the Translator Text Mining KP.
```

**Comment by cbizon** [comment]
@EvanDietzMorris @eKathleenCarter what's the status here?

**Comment by EvanDietzMorris** [comment]
I suspect this issue was initially due to us having an old version on the prod deployment, when we had already gotten the latest one up on dev. Previous discussions about this resulted in the conclusion that we did have the right thing. However, the long term updating process for tmkp is not great. We attempt to get the latest textmining kp from their google storage, and use the modified date as the version. If they change where they're putting the latest, or the file name changes, our pipeline will break and we won't have the latest anymore.

We use "edges.tsv.gz" from:
https://console.cloud.google.com/storage/browser/translator-text-workflow-dev-public/kgx/UniProt

**Comment by cbizon** [comment]
So can this issue be closed?

**Comment by EvanDietzMorris** [comment]
I think so, the potential issue with changing file name/location is not really specific to textminingkp, per say.
